#+AUTHOR: 204-351-724
#+TITLE: UCLA Philosophy 08: Paper Assignment #2
#+OPTIONS: toc:nil
#+OPTIONS: date:nil
#+OPTIONS: author:nil

#+LaTeX_CLASS_OPTIONS: [12pt,letter]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{times}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \doublespacing
#+LATEX_HEADER: \large

# Introduce Nelson Goodman's argument
# Explain that this is known as the new riddle of induction
In this paper I will discuss Nelson Goodman's new riddle of induction.
An inductive  argument is  a set  of premises  and a  conclusion.  Its
conclusion  is not  guaranteed  to  be true;  instead,  it holds  some
probability of being true.   This distinction differentiates inductive
and  deductive  arguments,  whose  conclusion, given  a  set  of  true
premises, is guaranteed to be true.

# Explain what the original problem of induction is

# Introduce the first premise of Goodman's argument
# Explain the Principle of the Uniformity of Nature
# Explain why the premise is true and justified
# Give an example of the first premise

Let us consider the argument, ``all observed emeralds have been green,
therefore, all  emeralds are  green.'' Suppose  that we  are scientist
studying the  nascent field of  gemology on another  planet, Prasinos.
On Prasinos, all past emerald observations have been green. We want to
make  an  inductive  argument  about emeralds  being  green.   It  was
originally argued  that in  order to  justify inductive  arguments, we
needed  to  rely  on  the  fact  that  the  universe  is  uniform  and
consistent.  In  other words, unobserved instances,  are like observed
instances.  We call this principle the uniformity of nature.

# What astronomer's see when they look through their telescopes
The philosopher David Hume argued that the principle of the uniformity
of nature is not justified. Since  the 17^{th} Century there have been
many attempts to justify the principle. It seems intuitive to say that
if  we  could justify  that  unobserved  instances are  like  observed
instances, then induction would be justified. Thus, if we could figure
out how  any two objects  in the universe  are uniform, we  could give
good inductive  arguments about how  they should behave  under certain
certain circumstances. If  we could take a bucket of  water from Earth
and a bucket  of water from Prasinos, we would  expect both buckets to
freeze at 0\textdegree Celsius.

# Introduce the second premise of Goodman's argument
# Explain why the PUN is insufficient to justify induction
# Explain why the premise is true and justified
# Give an example of the first premise

Goodman shows  us that the  principle of  the uniformity of  nature is
trivial. He argues that we can  select any two objects in the universe
and find something  about them that is uniform. For  example, a gopher
and a pair of headphones seem  like unrelated objects; however, as far
as  we  know   gophers  and  headphones  only  exist   on  Earth,  not
Prasinos. Thus, as Goodman argues,  the principle of the uniformity of
nature is a triviality; we can always find uniformity in nature.

Goodman argues  that there  is a  deeper problem at  the heart  of the
problem  of  induction.  Let  us  assume  that  the principle  of  the
uniformity of nature is true.  Let us consider two new words coined by
Goodman,  /grue/ and  /bleen/. Something  is  grue if  it is  observed
before  some  time  /t/  and  is  green;  otherwise  it  is  something
unobserved before time  /t/ and blue. Similarly,  something is /bleen/
if  before /t/  something is  observed to  be blue;  otherwise, it  is
unobserved before  /t/ and  green. Suppose  that we  set /t/  to March
2, 2084. Thus, the green sweater I  wore last Friday is both green and
grue, since  I observed  it before  2084. Similarly,  there is  a blue
emerald deep inside a cave that will not be found until at least 2084,
which is also grue.

# Introduce the third premise of Goodman's argument
# Give Goodman's argument for the word Grue
# Explain why the premise is true and justified
# Give an example of the first premise
We might have
thought  that since  we assumed  the  principle of  the uniformity  of
nature, we justified inductive arguments.  For example, we can add the
principle  uniformity of  nature  to our  original  argument: (i)  all
observed  emeralds have  been /green/,  (ii) unobserved  instances are
like    observed   instances,    (conclusion)    all   emeralds    are
/green/.  Remembering  that our  conclusion  is  not guaranteed,  only
probable, it seems that we have a good inductive argument. But Goodman
gives us a parallel inductive  argument using /grue/: (i) all observed
emeralds have been /grue/, (ii) unobserved instances are like observed
instances, (conclusion) all emeralds are /grue/.

We can  now appreciate Goodman's  riddle: given that the  principle of
the uniformity of  nature is trivially true, induction  still does not
work. We can see that the two inductive arguments above differ only in
their color  terms. Yet, it appears  that the former is  good argument
while  the latter  is  bad  argument. Since  the  form of  the
argument is the  same, we see that the principle  of the uniformity of
nature does not help us decide  which inductive arguments are good and
which ones are bad.

One natural response to Goodman's riddle attacks the peculiar words we
used in the  second argument. You could say that  words like green and
blue are projectable; they allow  us to make good inductive arguments.
Conversely, words like  grue and bleen are unprojectable;  they do not
allow us to make good inductive arguments. Because grue and bleen make
reference  to a  disjunctive  definition that  deals  with time,  they
contrast  with green  and  blue, which  make no  reference  to a  time
disjunction; however, this  fails to be a  convincing argument. First,
there does  not seem to  be good  reason why a  disjunctive definition
would have any bearing on inductive arguments. Second, we could define
green disjunctively:  something is  green if  it observed  before some
time /t/  and is grue,  or it is unobserved  before /t/ and  is bleen.
Thus, we  are left  with the inability  to distinguish  good inductive
arguments from bad  inductive arguments, despite the  principle of the
uniformity of nature.
