#+AUTHOR: 204-351-724
#+TITLE: UCLA Philosophy 08: Paper Assignment #4

#+OPTIONS: toc:nil
#+OPTIONS: date:nil
#+OPTIONS: author:nil

#+LaTeX_CLASS_OPTIONS: [12pt,letter]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{times}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \doublespacing
#+LATEX_HEADER: \large

In this paper I will discuss Carl Hempel and Paul Oppenheim's Inductive Statistical model (I-S model), which tells us what a good scientific explanation is.

Before discussing the I-S model, I would like to give an explanation that we can apply the model to later.
Recent psychological research has revealed that disrupting brain activity during sleep reduces your ability to form memories of experiences earlier in the day.
Let us call this (i) the sleep-memory association.
(ii) Carl is a pre-med student at UCLA.
(iii) Carl's classes require him to recall many facts about human anatomy.
Unfortunately, Carl is an insomniac and rarely gets more than three hours of continuous sleep.
Carl's sleep is constantly interrupted.
Keeping sleep deprived Carl in mind, let us now turn to the I-S model.

A scientific explanation requires premises that do the explaining and a conclusion, which needs to be explained.
We call the former explanantia and the latter the explanandum.
The explanantia and explanadum also need to be in the correct order.
Consider an explanation for why Carl did poorly during his last quarter, in which we swap premise (i) for our conclusion:
Carl is a student who needs to recall many facts.
Carl's sleep is constantly interrupted.
Therefore, we conclude the sleep-memory association.
But, this explanation does not explain the sleep-memory association.
Thus, it seems reasonable for a scientific explanation to have explanatia and an explanandum.

A good scientific explanation also requires its premises to be true.
Again, suppose we wanted an explanation for Carl's lousy academic performance last quarter.
Further suppose we used all the premises we had listed above as reasons to explain his performance but, in fact, it was not true that Carl sleeps poorly.
Then, it seems like a bad explanation to say that Carl did poorly this quarter because he does not sleep well, when in fact we know that Carl gets eight hours of sleep every night.
Thus, it seems reasonable to require scientific explanations have true premises.

The I-S model has a third requirement: at least one of the premises must be a statistical law of nature, without which the argument would not be valid.
The sleep-memory association premise is our explanation's statistical law of nature.
So, suppose that we omitted the sleep-memory association premise and run through the explanation, once more.
If the explanation seems to still work, you might be relying on intuition that is a statistical law.
Remember that the I-S model describes scientific explanations.
An explanation that relies on intuition is not a good scientific argument.

The I-S model also requires a scientific explanation to have empirically verifiable premises.
Suppose we said instead that an angel whispers to Carl wrong answers whenever he takes tests.
Given no way to verify supernatural phenomena, this explanation would not be a scientific explanation.
Thus, it seems reasonable that the I-S model requires empirically verifiable premises.

Finally, there is the requirement of maximum specificity, which says that an explanation must include relevant premises.
Consider the explanation about Carl's performance at school, adding a fourth premise: (iv) Carl has always done well in school, despite his insomnia.
Given this last premise, our conclusion that ``Carl did poorly during his last quarter at UCLA,'' seems unlikely and unjustified.
Thus, it seems reasonable to require a scientific explanation to include all relevant premises, since a conclusion's likelihood can be dramatically altered by a single premise.

But, there is a problem, however, with the requirement of maximum specificity; the requirement is vague.
It is difficult to say precisely what is relevant in an explanation and what is not.
Given our example explanation, what other information should we include about Carl?
We could include information about the time he goes to bed, the amount of noise in his room, the amount of REM sleep that he gets, or the quality of his mattress.
In short, there could be any number of premises that might influence the strength of the inductive argument.

Finally, let us consider a requirement that statistical explanations be strong inductive arguments.
If our statistical law about sleep and memory said that one percent of people with interrupted sleep have memory issues, our explanation would be poor.
Then, it seems reasonable to require that statistical explanation to be inductively strong arguments; however, this requirement runs into issues in other seemingly good scientific explanations.

Epidemiologists are worried about the Olympics games being held in Brazil.
Recent studies predict that for evert 100,000 people that visit the games, 50 people will be infected with the Zika virus.
Suppose that Carl contracts the virus and we explain how he got it: 
(i) people who visit Brazil have a small chance of contracting the Zika virus,
(ii) Carl visited Brazil, 
(therefore) Carl contracted the Zika virus.
This explanation meets all the requirements of the I-S model, yet opinions differ about its classification.
A lay person might say that explanation is poor, while an epidemiologist might say it is good.
Thus, the requirement seems to work for some explanations and fail for others.

We have seen that the I-S model provides us with reasonable requirements for what constitutes a scientific explanation.
The model worked well for our first explanation but suffers from several problems: 
(i) it is difficult to say what is relevant in a scientific explanation, and 
(ii) we do not know whether we should always require explanations to be inductively strong arguments. 
